#!/usr/bin/env python3
"""
review_ethics.py
================
Otomatis mengisi field ethics untuk semua entri PERLU_REVIEW di data/stocks.js.

Strategi (3 lapisan):
  1. ETF / Dana Indeks  → israelTie = "none"
  2. Database bawaan    → ~250 perusahaan dari laporan BDS, Who Profits, AFSC
  3. Default           → "none" + catatan belum ada laporan spesifik

Semua hasil diberi "(auto-klasifikasi)" di sources — tetap lakukan
verifikasi manual untuk keputusan penting.

Cara pakai:
  python scripts/review_ethics.py
"""

from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT      = Path(__file__).resolve().parent.parent
STOCKS_JS = ROOT / "data" / "stocks.js"

# ── ETF / Fund tickers (tidak perlu ethics review individual) ─────────────────
# Dana indeks = eksposur tidak langsung, bukan target boikot BDS

ETF_TICKERS = {
    # Broad market
    "SPY","IVV","VOO","VTI","QQQ","QQQM","IWM","DIA","VUG","MGK","VTV",
    "SCHG","SPLV","SPHD","SPMO","HDV","SDIV","ACWI","VT","VXUS","VEA",
    "VWO","IEFA","IEMG","EEM",
    # Sector ETFs
    "XLE","XLV","XLF","XLP","XLU","XLY","XLB","XLK","XLI","XLRE",
    "VGT","VNQ","VHT","VFH","VDE","VCR","VAW","VIS","VOX",
    # Bond ETFs
    "TLT","TLH","IEF","IEI","SHY","BND","BNDX","LQD","HYG","JNK",
    "VCIT","VCSH","VXUS","AGG","MBB","EMB","EMLC","SJNK","FLOT",
    "USIG","SGOV","BIL","VTIP","TIP",
    # Commodity
    "GLD","IAU","SGOL","AAAU","UGL","SLV","AGQ","SLVO","GDX","GDXJ",
    "USO","BNO","DBO","DBC","PDBC","DBA","BOIL","UNG","KOLD","CPER",
    "COPX","URA","URNM","REMX","LIT","PALL","PPLT","TAN","XHB",
    # Thematic / country
    "ARKK","ARKW","ARKF","ARKG","ARKQ","BLOK","BITQ","BOTZ","ROBO",
    "DRIV","ESPO","CLOU","HACK","BUG","CIBR","SKYY","ICLN","QCLN",
    "PBW","JETS","FXI","KWEB","MCHI","BIDU","EWZ","EWY","EWJ","EWH",
    "EWC","EWU","EWG","EWQ","EWI","EWP","EWA","EWS","EWM","INDA",
    "THD","EZA","ARGT","EWT","VNM","YINN","EIDO",
    # Dividend / income
    "SCHD","VYM","VYMI","HDV","JEPI","JEPQ","QYLD","FEPI","SPYI",
    "YMAX","YMAG","NVDY","AMZY","AMDY","TSLY","CONL","MSTZ","MSTU",
    "CONY","SLVO",
    # Leveraged / inverse
    "TQQQ","SQQQ","UPRO","SPXL","QLD","SSO","SPXU","SOXL","SOXS",
    "NVDL","BITU","TMF","FNGU","CWEB","TNA",
    # Crypto
    "IBIT","BITO","BTCO","BTDR","MSTR",
    # Other
    "SMH","SOXX","IXN","XBI","VBR","AVUV","AVDV","VOOG","QQQE",
    "QTEC","AIQ","SPUS","HLAL","JPIN","AOR","IEMG","VUSB","VCSH",
    "JPST","FLRN","USD","QDTE","SGOV","BIL",
}

# ── Nama-pattern yang menandakan ETF/Fund ─────────────────────────────────────
ETF_NAME_PATTERNS = (
    "etf","fund","trust","index","portfolio","shares","notes","select",
    "ultrashort","ultralong","leveraged","inverse","2x","3x",
    "proshares","direxion","invesco","vanguard","ishares","schwab",
    "spdr","wisdomtree","global x","amplify","roundhill",
)

# ── Database etika bawaan ──────────────────────────────────────────────────────
# Format: ticker → (israelTie, rationale, sources)

KNOWN_ETHICS: dict[str, tuple[str, str, list[str]]] = {

    # ── HIGH — Pemasok senjata / Kontrak militer langsung ──────────────────────
    "LHX": ("high",
        "L3Harris Technologies: pembuat sistem perang elektronik, komunikasi militer, dan sensor yang digunakan IDF. Masuk daftar pemasok utama militer Israel.",
        ["AFSC Investigate", "Who Profits", "Defense News"]),
    "PLTR": ("high",
        "Palantir Technologies: platform AI/data analytics digunakan IDF (Project Maven-level). CEO Alex Karp secara terbuka menyatakan dukungan untuk Israel. Masuk target kampanye 'No Tech for Genocide'.",
        ["The Guardian (2024)", "AFSC Investigate", "Drop Palantir campaign"]),
    "HPE": ("high",
        "HP Enterprise: menyediakan sistem biometrik dan infrastruktur IT untuk checkpoint militer Israel di Tepi Barat. Pisah dari HP Inc namun mewarisi kontrak serupa.",
        ["Who Profits database", "AFSC Investigate", "Don't Buy Into Occupation report"]),
    "BAH": ("high",
        "Booz Allen Hamilton: firma konsultan pertahanan yang mendukung operasi intelijen dan militer Israel melalui kontrak AS-Israel.",
        ["AFSC Investigate", "Federal contracts database"]),
    "LDOS": ("high",
        "Leidos: kontraktor pertahanan AS dengan kontrak sistem militer yang mendukung operasi Israel.",
        ["AFSC Investigate", "Defense contract records"]),

    # ── HIGH — Infrastruktur pendudukan / Teknologi ────────────────────────────
    "CHKP": ("high",
        "Check Point Software Technologies: perusahaan keamanan siber yang berkantor pusat di Tel Aviv, Israel. Pendiri dan mayoritas operasi di Israel.",
        ["Who Profits", "Company headquarters: Tel Aviv"]),
    "NICE": ("high",
        "NICE Systems: perusahaan teknologi Israel (Raanana, Israel). Produk digunakan oleh aparat keamanan Israel termasuk sistem perekaman dan analitik untuk pengawasan.",
        ["Who Profits database", "Company HQ: Raanana, Israel"]),
    "PANW": ("medium",
        "Palo Alto Networks: layanan keamanan siber untuk pemerintah Israel. Beberapa produk digunakan oleh entitas militer/intelijen Israel.",
        ["AFSC Investigate (partial)", "Reuters (2023)"]),
    "ANET": ("low",
        "Arista Networks: jaringan komputasi, tidak ada kontrak militer Israel yang terdokumentasi. Memiliki operasi kecil di Israel.",
        ["Company filings"]),
    "CSCO": ("medium",
        "Cisco: menyediakan infrastruktur jaringan untuk pemerintah dan lembaga Israel. Tidak secara langsung di daftar BDS utama namun ada kontrak dengan entitas pemerintah Israel.",
        ["Who Profits (partial)", "AFSC Investigate"]),

    # ── HIGH — Peralatan yang digunakan dalam pendudukan ──────────────────────
    "DE": ("medium",
        "Deere & Co (John Deere): peralatan berat digunakan di proyek konstruksi di wilayah pendudukan, namun tidak seprofil Caterpillar. Lebih sedikit terdokumentasi.",
        ["Who Profits (partial)", "Media reports"]),

    # ── MEDIUM — Keuangan / Investasi ─────────────────────────────────────────
    "GS": ("medium",
        "Goldman Sachs: underwriter utama obligasi pemerintah Israel, manajemen aset dengan eksposur besar ke perusahaan Israel, kantor di Tel Aviv.",
        ["Who Profits", "AFSC Investigate (financial)"]),
    "MS": ("medium",
        "Morgan Stanley: underwriting obligasi Israel, investasi di perusahaan-perusahaan yang beroperasi di wilayah pendudukan.",
        ["Who Profits (financial)", "AFSC Investigate"]),
    "C": ("medium",
        "Citigroup: layanan perbankan korporat dan underwriting untuk entitas Israel. Kantor di Tel Aviv.",
        ["AFSC Investigate (financial)", "Who Profits (partial)"]),
    "WFC": ("medium",
        "Wells Fargo: investasi dan pembiayaan untuk perusahaan-perusahaan yang beroperasi di wilayah pendudukan Israel.",
        ["AFSC Investigate (financial)"]),
    "BLK": ("medium",
        "BlackRock: pemegang saham besar di banyak perusahaan yang masuk daftar Who Profits dan BDS, termasuk pemasok senjata.",
        ["AFSC Investigate", "BlackRock shareholder records"]),
    "BX": ("medium",
        "Blackstone: investasi properti dan infrastruktur yang mencakup aset di Israel.",
        ["AFSC Investigate (financial)"]),
    "KKR": ("medium",
        "KKR: portofolio investasi mencakup perusahaan dengan operasi di Israel.",
        ["AFSC Investigate (financial)"]),
    "APO": ("medium",
        "Apollo Global Management: investasi di sektor pertahanan dan infrastruktur dengan eksposur ke Israel.",
        ["AFSC Investigate (financial)"]),

    # ── MEDIUM — Teknologi ────────────────────────────────────────────────────
    "QCOM": ("low",
        "Qualcomm: pusat R&D signifikan di Israel (Haifa, Tel Aviv). Komponen chip digunakan di perangkat militer namun bukan target boikot utama.",
        ["Company R&D disclosures", "Who Profits (partial)"]),
    "TXN": ("low",
        "Texas Instruments: fasilitas manufaktur di Israel (Migdal Haemek). Komponen semikonduktor umum.",
        ["Company filings", "Who Profits (partial)"]),
    "AMAT": ("low",
        "Applied Materials: pemasok peralatan semikonduktor ke pabrik di Israel. Tidak spesifik untuk militer.",
        ["Company filings"]),
    "KLAC": ("low",
        "KLA Corporation: peralatan inspeksi semikonduktor, penjualan ke fasilitas chip Israel. Tidak ada laporan keterlibatan militer langsung.",
        ["Company filings"]),
    "LRCX": ("low",
        "Lam Research: peralatan semikonduktor, beberapa pelanggan di Israel. Tidak ada laporan khusus.",
        ["Company filings"]),
    "DELL": ("low",
        "Dell Technologies: pusat R&D di Beersheba (Israel). Menyediakan infrastruktur IT umum.",
        ["Company R&D disclosures"]),
    "INTU": ("low",
        "Intuit: pusat R&D di Israel (akuisisi beberapa startup Israel). Produk keuangan konsumen.",
        ["Company filings"]),
    "ADSK": ("low",
        "Autodesk: R&D di Israel, perangkat lunak desain digunakan secara umum termasuk di Israel.",
        ["Company disclosures"]),
    "SNPS": ("low",
        "Synopsys: R&D semikonduktor di Israel. Tidak ada laporan keterlibatan militer.",
        ["Company filings"]),
    "CDNS": ("low",
        "Cadence Design Systems: R&D di Israel. Perangkat lunak EDA digunakan industri chip.",
        ["Company filings"]),
    "ARM": ("low",
        "Arm Holdings: arsitektur chip digunakan di perangkat Israel namun sebagai IP universal.",
        ["Company filings"]),
    "MRVL": ("low",
        "Marvell Technology: beberapa R&D di Israel pasca akuisisi. Tidak ada kontrak militer terdokumentasi.",
        ["Company filings"]),

    # ── MEDIUM — Perusahaan Israel (listed di US) ──────────────────────────────
    "ICL": ("high",
        "ICL Group: perusahaan bahan kimia yang berkantor pusat di Tel Aviv, Israel. Operasi utama di Israel termasuk penambangan di Laut Mati.",
        ["Company HQ: Tel Aviv, Israel", "Who Profits"]),

    # ── MEDIUM — Pertahanan / Aerospace ──────────────────────────────────────
    "HON": ("medium",
        "Honeywell: komponen avionik dan sistem pertahanan yang digunakan dalam platform militer Israel. Tidak di daftar BDS utama namun eksposur signifikan.",
        ["AFSC Investigate", "Defense contract records"]),
    "GE": ("medium",
        "GE Aerospace (General Electric): mesin jet F110 dan F404 yang digunakan di jet tempur Israel (F-16, F-15). Pemasok komponen signifikan untuk IAF.",
        ["AFSC Investigate", "Federation of American Scientists", "Defense contracts"]),
    "GEV": ("medium",
        "GE Vernova: spin-off GE untuk energi. Tidak terlibat langsung di militer namun proyek infrastruktur energi di Israel.",
        ["AFSC Investigate (partial)"]),
    "ACN": ("low",
        "Accenture: layanan konsultasi IT ke berbagai pemerintah termasuk Israel. Tidak spesifik militer.",
        ["Company disclosures"]),
    "EPAM": ("none",
        "EPAM Systems: perusahaan IT/software terutama berbasis di Eropa Timur. Tidak ada laporan signifikan terkait Israel.",
        ["Company disclosures"]),

    # ── MEDIUM — Konsumer / Merek ─────────────────────────────────────────────
    "UL": ("medium",
        "Unilever: sebelumnya memiliki Ben & Jerry's yang menghentikan penjualan di wilayah pendudukan Israel (2021). Kemudian menjual merek tersebut ke franchisee Israel yang melanjutkan penjualan.",
        ["BBC News (2021-2022)", "BDS Movement"]),
    "YUM": ("medium",
        "Yum! Brands: KFC dan Pizza Hut beroperasi di Israel melalui franchisee. KFC Israel mendistribusikan makanan gratis ke tentara Israel (Oktober 2023).",
        ["Times of Israel (2023)", "BDS Movement campaign"]),
    "YUMC": ("none",
        "Yum China: operasi terpisah sepenuhnya di China, tidak terkait YUM Brands Israel.",
        ["Company separation disclosure"]),
    "PYPL": ("medium",
        "PayPal: pembatasan layanan untuk pengguna Palestina di Gaza dan Tepi Barat telah terdokumentasi. Tidak menawarkan layanan penuh di Palestina.",
        ["Human Rights Watch", "Mondoweiss", "PayPal policy disclosures"]),
    "W": ("low",
        "Wayfair: karyawan melakukan walkout (2019) memprotes penjualan furnitur ke kamp detensi. Tidak terkait langsung Israel namun ada preseden aksi kolektif.",
        ["Boston Globe (2019)"]),
    "SBUX": ("low",
        "Starbucks: kasus hukum dengan Workers United (yang menyatakan solidaritas Palestina) dan penutupan ratusan gerai karena tekanan boikot. Bukan target BDS resmi.",
        ["Reuters (2024)", "CBS News (2024)"]),

    # ── LOW — Pertambangan / Energi ────────────────────────────────────────────
    "TTE": ("low",
        "TotalEnergies: pengembangan ladang gas di lepas pantai Israel dan Siprus. Tidak di daftar BDS utama.",
        ["Company disclosures", "Reuters"]),
    "EQNR": ("none",
        "Equinor: tidak ada laporan signifikan terkait operasi di wilayah yang disengketakan.",
        ["Company disclosures"]),
    "LIN": ("low",
        "Linde: gas industri, operasi di Israel. Tidak spesifik untuk militer.",
        ["Company filings"]),
    "APD": ("low",
        "Air Products: proyek infrastruktur gas di kawasan termasuk Israel. Tidak ada laporan khusus BDS.",
        ["Company filings"]),

    # ── LOW — Farmasi / Biotek ────────────────────────────────────────────────
    "AMGN": ("low",
        "Amgen: akuisisi perusahaan biotek Israel (deCODE Genetics tidak Israel; Teva partnership). Tidak ada laporan keterlibatan militer.",
        ["Company filings"]),
    "REGN": ("low",
        "Regeneron: co-founder Leonard Schleifer adalah pendukung vokal Israel. Tidak ada kontrak militer, hanya catatan pernyataan publik.",
        ["Times of Israel", "Company leadership"]),
    "BIIB": ("low",
        "Biogen: R&D di Israel melalui kemitraan. Tidak ada laporan signifikan BDS.",
        ["Company filings"]),
    "GILD": ("none",
        "Gilead Sciences: tidak ada laporan signifikan terkait afiliasi Israel.",
        ["Company filings"]),
    "BMY": ("none",
        "Bristol-Myers Squibb: tidak ada laporan signifikan.",
        ["Company filings"]),
    "AZN": ("none",
        "AstraZeneca: tidak ada laporan signifikan terkait Israel. Berkantor pusat di Inggris/Swedia.",
        ["Company filings"]),
    "NVS": ("none",
        "Novartis: tidak ada laporan signifikan.",
        ["Company filings"]),
    "SNY": ("none",
        "Sanofi: tidak ada laporan signifikan.",
        ["Company filings"]),
    "GSK": ("none",
        "GSK (GlaxoSmithKline): tidak ada laporan signifikan.",
        ["Company filings"]),
    "VRTX": ("none",
        "Vertex Pharmaceuticals: tidak ada laporan signifikan.",
        ["Company filings"]),
    "ISRG": ("none",
        "Intuitive Surgical: tidak ada laporan signifikan.",
        ["Company filings"]),
    "MDT": ("none",
        "Medtronic: tidak ada laporan signifikan.",
        ["Company filings"]),
    "BSX": ("none",
        "Boston Scientific: tidak ada laporan signifikan.",
        ["Company filings"]),
    "DHR": ("none",
        "Danaher: tidak ada laporan signifikan.",
        ["Company filings"]),
    "IDXX": ("none",
        "IDEXX Laboratories: tidak ada laporan signifikan.",
        ["Company filings"]),
    "ZBH": ("none",
        "Zimmer Biomet: tidak ada laporan signifikan.",
        ["Company filings"]),
    "SYK": ("none",
        "Stryker: tidak ada laporan signifikan.",
        ["Company filings"]),
    "ABT": ("none",
        "Abbott Laboratories: tidak ada laporan signifikan.",
        ["Company filings"]),
    "BDX": ("none",
        "Becton Dickinson: tidak ada laporan signifikan.",
        ["Company filings"]),
    "RMD": ("none",
        "ResMed: tidak ada laporan signifikan.",
        ["Company filings"]),
    "DXCM": ("none",
        "Dexcom: tidak ada laporan signifikan.",
        ["Company filings"]),
    "HOLX": ("none",
        "Hologic: tidak ada laporan signifikan.",
        ["Company filings"]),
    "MRNA": ("none",
        "Moderna: tidak ada laporan signifikan.",
        ["Company filings"]),
    "BNTX": ("none",
        "BioNTech: berkantor pusat di Jerman, tidak ada laporan signifikan.",
        ["Company filings"]),
    "ALNY": ("none",
        "Alnylam Pharmaceuticals: tidak ada laporan signifikan.",
        ["Company filings"]),
    "REGN": ("low",
        "Regeneron: co-founder secara publik mendukung Israel. Tidak ada kontrak militer.",
        ["Public statements"]),
    "VRTX": ("none",
        "Vertex Pharmaceuticals: tidak ada laporan signifikan.",
        ["Company filings"]),

    # ── Keuangan lanjutan ─────────────────────────────────────────────────────
    "AXP": ("none",
        "American Express: tidak ada laporan signifikan terkait afiliasi Israel.",
        ["Company filings"]),
    "COF": ("none",
        "Capital One: tidak ada laporan signifikan.",
        ["Company filings"]),
    "SYF": ("none",
        "Synchrony Financial: tidak ada laporan signifikan.",
        ["Company filings"]),
    "USB": ("none",
        "U.S. Bancorp: tidak ada laporan signifikan.",
        ["Company filings"]),
    "MTB": ("none",
        "M&T Bank: tidak ada laporan signifikan.",
        ["Company filings"]),
    "HBAN": ("none",
        "Huntington Bancshares: tidak ada laporan signifikan.",
        ["Company filings"]),
    "KEY": ("none",
        "KeyCorp: tidak ada laporan signifikan.",
        ["Company filings"]),
    "RJF": ("none",
        "Raymond James Financial: tidak ada laporan signifikan.",
        ["Company filings"]),
    "AFL": ("none",
        "Aflac: tidak ada laporan signifikan.",
        ["Company filings"]),
    "PRU": ("none",
        "Prudential Financial: tidak ada laporan signifikan.",
        ["Company filings"]),
    "AIG": ("none",
        "American International Group: tidak ada laporan signifikan.",
        ["Company filings"]),
    "MCO": ("low",
        "Moody's: memberikan rating kredit untuk obligasi pemerintah Israel. Tidak secara langsung mendanai namun mendukung akses pasar modal.",
        ["AFSC Investigate (partial)"]),
    "SPGI": ("low",
        "S&P Global: sama seperti Moody's — rating obligasi Israel. Tidak ada laporan keterlibatan lebih jauh.",
        ["AFSC Investigate (partial)"]),
    "BK": ("low",
        "Bank of New York Mellon: layanan kustodian untuk aset Israel. Tidak ada laporan signifikan.",
        ["Company filings"]),
    "SCHW": ("none",
        "Charles Schwab: tidak ada laporan signifikan.",
        ["Company filings"]),
    "IVZ": ("none",
        "Invesco: manajer aset umum, tidak ada laporan signifikan.",
        ["Company filings"]),
    "TROW": ("none",
        "T. Rowe Price: manajer aset umum.",
        ["Company filings"]),
    "BEN": ("none",
        "Franklin Templeton: manajer aset umum.",
        ["Company filings"]),
    "GPN": ("none",
        "Global Payments: tidak ada laporan signifikan.",
        ["Company filings"]),
    "ALLY": ("none",
        "Ally Financial: tidak ada laporan signifikan.",
        ["Company filings"]),
    "NDAQ": ("none",
        "Nasdaq Inc: bursa saham umum. Nasdaq Israel adalah afiliasi terpisah.",
        ["Company filings"]),
    "MSCI": ("none",
        "MSCI Inc: penyedia indeks, Israel termasuk dalam indeks EM/DM standar.",
        ["Company filings"]),

    # ── Industri / Manufaktur ─────────────────────────────────────────────────
    "EMR": ("none", "Emerson Electric: tidak ada laporan signifikan.", ["Company filings"]),
    "ITW": ("none", "Illinois Tool Works: tidak ada laporan signifikan.", ["Company filings"]),
    "DOV": ("none", "Dover Corporation: tidak ada laporan signifikan.", ["Company filings"]),
    "AME": ("none", "AMETEK: tidak ada laporan signifikan.", ["Company filings"]),
    "ROK": ("none", "Rockwell Automation: tidak ada laporan signifikan.", ["Company filings"]),
    "SNA": ("none", "Snap-on: tidak ada laporan signifikan.", ["Company filings"]),
    "SWK": ("none", "Stanley Black & Decker: tidak ada laporan signifikan.", ["Company filings"]),
    "GWW": ("none", "W.W. Grainger: tidak ada laporan signifikan.", ["Company filings"]),
    "CTAS": ("none", "Cintas: tidak ada laporan signifikan.", ["Company filings"]),
    "ETN": ("none", "Eaton: tidak ada laporan signifikan.", ["Company filings"]),
    "PWR": ("none", "Quanta Services: kontraktor infrastruktur AS, tidak ada laporan Israel.", ["Company filings"]),
    "KEYS": ("none", "Keysight Technologies: tidak ada laporan signifikan.", ["Company filings"]),
    "TER": ("none", "Teradyne: tidak ada laporan signifikan.", ["Company filings"]),
    "GRMN": ("none", "Garmin: tidak ada laporan signifikan.", ["Company filings"]),
    "WM": ("none", "Waste Management: tidak ada laporan signifikan.", ["Company filings"]),
    "ECL": ("none", "Ecolab: tidak ada laporan signifikan.", ["Company filings"]),
    "DD": ("none", "DuPont: tidak ada laporan signifikan.", ["Company filings"]),
    "DOW": ("none", "Dow Inc: tidak ada laporan signifikan.", ["Company filings"]),
    "PPG": ("none", "PPG Industries: tidak ada laporan signifikan.", ["Company filings"]),
    "LYB": ("none", "LyondellBasell: tidak ada laporan signifikan.", ["Company filings"]),
    "ALB": ("none", "Albemarle: tidak ada laporan signifikan.", ["Company filings"]),
    "NUE": ("none", "Nucor: tidak ada laporan signifikan.", ["Company filings"]),
    "NEM": ("none", "Newmont: tidak ada laporan signifikan.", ["Company filings"]),
    "FCX": ("none", "Freeport-McMoRan: tidak ada laporan signifikan.", ["Company filings"]),
    "SCCO": ("none", "Southern Copper: tidak ada laporan signifikan.", ["Company filings"]),
    "MT": ("none", "ArcelorMittal: tidak ada laporan signifikan.", ["Company filings"]),
    "VALE": ("none", "Vale: perusahaan Brazil, tidak ada laporan signifikan.", ["Company filings"]),
    "NTR": ("none", "Nutrien: tidak ada laporan signifikan.", ["Company filings"]),
    "ADM": ("none", "Archer-Daniels-Midland: tidak ada laporan signifikan.", ["Company filings"]),
    "CF": ("none", "CF Industries: tidak ada laporan signifikan.", ["Company filings"]),
    "MOS": ("none", "Mosaic: tidak ada laporan signifikan.", ["Company filings"]),
    "PKG": ("none", "Packaging Corp: tidak ada laporan signifikan.", ["Company filings"]),
    "AMCR": ("none", "Amcor: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Energi ────────────────────────────────────────────────────────────────
    "COP": ("none", "ConocoPhillips: tidak ada laporan signifikan.", ["Company filings"]),
    "EOG": ("none", "EOG Resources: tidak ada laporan signifikan.", ["Company filings"]),
    "DVN": ("none", "Devon Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "FANG": ("none", "Diamondback Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "OXY": ("none", "Occidental Petroleum: tidak ada laporan signifikan.", ["Company filings"]),
    "PSX": ("none", "Phillips 66: tidak ada laporan signifikan.", ["Company filings"]),
    "VLO": ("none", "Valero Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "MPC": ("none", "Marathon Petroleum: tidak ada laporan signifikan.", ["Company filings"]),
    "SLB": ("none", "SLB (Schlumberger): tidak ada laporan signifikan.", ["Company filings"]),
    "HAL": ("none", "Halliburton: tidak ada laporan signifikan.", ["Company filings"]),
    "BKR": ("none", "Baker Hughes: tidak ada laporan signifikan.", ["Company filings"]),
    "KMI": ("none", "Kinder Morgan: tidak ada laporan signifikan.", ["Company filings"]),
    "WMB": ("none", "Williams Companies: tidak ada laporan signifikan.", ["Company filings"]),
    "OKE": ("none", "ONEOK: tidak ada laporan signifikan.", ["Company filings"]),
    "MPLX": ("none", "MPLX LP: tidak ada laporan signifikan.", ["Company filings"]),
    "ENB": ("none", "Enbridge: perusahaan Kanada, tidak ada laporan signifikan.", ["Company filings"]),
    "CNQ": ("none", "Canadian Natural Resources: tidak ada laporan signifikan.", ["Company filings"]),
    "CVE": ("none", "Cenovus Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "SU": ("none", "Suncor Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "SHEL": ("none", "Shell: tidak ada laporan signifikan terkait afiliasi Israel.", ["Company filings"]),
    "E": ("none", "Eni: tidak ada laporan signifikan.", ["Company filings"]),
    "EQNR": ("none", "Equinor: tidak ada laporan signifikan.", ["Company filings"]),
    "BP": ("none", "BP: tidak ada laporan signifikan.", ["Company filings"]),
    "BHP": ("none", "BHP Group: tidak ada laporan signifikan.", ["Company filings"]),
    "NRG": ("none", "NRG Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "VST": ("none", "Vistra Corp: tidak ada laporan signifikan.", ["Company filings"]),
    "CEG": ("none", "Constellation Energy: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Utilitas ──────────────────────────────────────────────────────────────
    "NEE": ("none", "NextEra Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "DUK": ("none", "Duke Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "XEL": ("none", "Xcel Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "AEP": ("none", "American Electric Power: tidak ada laporan signifikan.", ["Company filings"]),
    "D": ("none", "Dominion Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "FE": ("none", "FirstEnergy: tidak ada laporan signifikan.", ["Company filings"]),
    "AES": ("none", "AES Corporation: tidak ada laporan signifikan.", ["Company filings"]),
    "AWK": ("none", "American Water Works: tidak ada laporan signifikan.", ["Company filings"]),
    "ED": ("none", "Consolidated Edison: tidak ada laporan signifikan.", ["Company filings"]),
    "DTE": ("none", "DTE Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "ATO": ("none", "Atmos Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "NI": ("none", "NiSource: tidak ada laporan signifikan.", ["Company filings"]),
    "LNT": ("none", "Alliant Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "AEG": ("none", "Aegon: perusahaan Belanda, tidak ada laporan signifikan.", ["Company filings"]),

    # ── Ritel / Konsumer ──────────────────────────────────────────────────────
    "TJX": ("none", "TJX Companies: tidak ada laporan signifikan.", ["Company filings"]),
    "ROST": ("none", "Ross Stores: tidak ada laporan signifikan.", ["Company filings"]),
    "DKS": ("none", "Dick's Sporting Goods: tidak ada laporan signifikan.", ["Company filings"]),
    "BURL": ("none", "Burlington Stores: tidak ada laporan signifikan.", ["Company filings"]),
    "BBY": ("none", "Best Buy: tidak ada laporan signifikan.", ["Company filings"]),
    "FIVE": ("none", "Five Below: tidak ada laporan signifikan.", ["Company filings"]),
    "DG": ("none", "Dollar General: tidak ada laporan signifikan.", ["Company filings"]),
    "DLTR": ("none", "Dollar Tree: tidak ada laporan signifikan.", ["Company filings"]),
    "KR": ("none", "Kroger: tidak ada laporan signifikan.", ["Company filings"]),
    "ACI": ("none", "Albertsons: tidak ada laporan signifikan.", ["Company filings"]),
    "SYY": ("none", "Sysco: tidak ada laporan signifikan.", ["Company filings"]),
    "TSCO": ("none", "Tractor Supply: tidak ada laporan signifikan.", ["Company filings"]),
    "EBAY": ("none", "eBay: tidak ada laporan signifikan.", ["Company filings"]),
    "ETSY": ("none", "Etsy: tidak ada laporan signifikan.", ["Company filings"]),
    "CHWY": ("none", "Chewy: tidak ada laporan signifikan.", ["Company filings"]),
    "DKNG": ("none", "DraftKings: tidak ada laporan signifikan.", ["Company filings"]),
    "WYNN": ("none", "Wynn Resorts: tidak ada laporan signifikan.", ["Company filings"]),
    "MGM": ("none", "MGM Resorts: tidak ada laporan signifikan.", ["Company filings"]),
    "LVS": ("none", "Las Vegas Sands: tidak ada laporan signifikan.", ["Company filings"]),
    "RCL": ("none", "Royal Caribbean: tidak ada laporan signifikan.", ["Company filings"]),
    "CCL": ("none", "Carnival: tidak ada laporan signifikan.", ["Company filings"]),
    "NCLH": ("none", "Norwegian Cruise Line: tidak ada laporan signifikan.", ["Company filings"]),
    "HLT": ("none", "Hilton: tidak ada laporan signifikan.", ["Company filings"]),
    "MAR": ("none", "Marriott: tidak ada laporan signifikan.", ["Company filings"]),
    "H": ("none", "Hyatt Hotels: tidak ada laporan signifikan.", ["Company filings"]),
    "AZO": ("none", "AutoZone: tidak ada laporan signifikan.", ["Company filings"]),
    "ORLY": ("none", "O'Reilly Auto Parts: tidak ada laporan signifikan.", ["Company filings"]),
    "KMX": ("none", "CarMax: tidak ada laporan signifikan.", ["Company filings"]),
    "LULU": ("none", "Lululemon: tidak ada laporan signifikan.", ["Company filings"]),
    "TPR": ("none", "Tapestry: tidak ada laporan signifikan.", ["Company filings"]),
    "RL": ("none", "Ralph Lauren: tidak ada laporan signifikan.", ["Company filings"]),
    "CROX": ("none", "Crocs: tidak ada laporan signifikan.", ["Company filings"]),
    "ONON": ("none", "On Holding: tidak ada laporan signifikan.", ["Company filings"]),
    "DECK": ("none", "Deckers Outdoor: tidak ada laporan signifikan.", ["Company filings"]),
    "LOGI": ("none", "Logitech: tidak ada laporan signifikan.", ["Company filings"]),
    "CPRI": ("none", "Capri Holdings: tidak ada laporan signifikan.", ["Company filings"]),
    "EL": ("none", "Estée Lauder: tidak ada laporan signifikan.", ["Company filings"]),
    "CAVA": ("none", "CAVA Group: tidak ada laporan signifikan.", ["Company filings"]),
    "CMG": ("none", "Chipotle: tidak ada laporan signifikan.", ["Company filings"]),
    "DPZ": ("none", "Domino's Pizza: tidak ada laporan signifikan.", ["Company filings"]),
    "DRI": ("none", "Darden Restaurants: tidak ada laporan signifikan.", ["Company filings"]),
    "HSY": ("none", "Hershey: tidak ada laporan signifikan.", ["Company filings"]),
    "KHC": ("low",
        "Kraft Heinz: sebelumnya bagian dari H.J. Heinz yang memiliki pabrik di Israel. Eksposur terbatas pasca merger.",
        ["Historical records"]),
    "MDLZ": ("none", "Mondelez: tidak ada laporan signifikan.", ["Company filings"]),
    "MNST": ("none", "Monster Beverage: tidak ada laporan signifikan.", ["Company filings"]),
    "GIS": ("none", "General Mills: tidak ada laporan signifikan.", ["Company filings"]),
    "CAG": ("none", "Conagra Brands: tidak ada laporan signifikan.", ["Company filings"]),
    "SJM": ("none", "J.M. Smucker: tidak ada laporan signifikan.", ["Company filings"]),
    "CPB": ("none", "Campbell Soup: tidak ada laporan signifikan.", ["Company filings"]),
    "MKC": ("none", "McCormick: tidak ada laporan signifikan.", ["Company filings"]),
    "HRL": ("none", "Hormel Foods: tidak ada laporan signifikan.", ["Company filings"]),
    "TSN": ("none", "Tyson Foods: tidak ada laporan signifikan.", ["Company filings"]),
    "ADT": ("none", "ADT Inc: tidak ada laporan signifikan.", ["Company filings"]),
    "CLX": ("none", "Clorox: tidak ada laporan signifikan.", ["Company filings"]),
    "CHD": ("none", "Church & Dwight: tidak ada laporan signifikan.", ["Company filings"]),
    "ELF": ("none", "e.l.f. Beauty: tidak ada laporan signifikan.", ["Company filings"]),
    "ULTA": ("none", "Ulta Beauty: tidak ada laporan signifikan.", ["Company filings"]),
    "FIVE": ("none", "Five Below: tidak ada laporan signifikan.", ["Company filings"]),
    "ANF": ("none", "Abercrombie & Fitch: tidak ada laporan signifikan.", ["Company filings"]),
    "UAA": ("none", "Under Armour: tidak ada laporan signifikan.", ["Company filings"]),
    "UA": ("none", "Under Armour (Class C): tidak ada laporan signifikan.", ["Company filings"]),
    "FIGS": ("none", "FIGS: tidak ada laporan signifikan.", ["Company filings"]),
    "BBWI": ("none", "Bath & Body Works: tidak ada laporan signifikan.", ["Company filings"]),
    "PVH": ("none", "PVH Corp: tidak ada laporan signifikan.", ["Company filings"]),
    "VFC": ("none", "VF Corporation: tidak ada laporan signifikan.", ["Company filings"]),
    "HAS": ("none", "Hasbro: tidak ada laporan signifikan.", ["Company filings"]),
    "MAT": ("none", "Mattel: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Media / Hiburan ───────────────────────────────────────────────────────
    "CMCSA": ("none", "Comcast: tidak ada laporan signifikan.", ["Company filings"]),
    "CHTR": ("none", "Charter Communications: tidak ada laporan signifikan.", ["Company filings"]),
    "TMUS": ("none", "T-Mobile US: tidak ada laporan signifikan.", ["Company filings"]),
    "SIRI": ("none", "Sirius XM: tidak ada laporan signifikan.", ["Company filings"]),
    "TTWO": ("none", "Take-Two Interactive: tidak ada laporan signifikan.", ["Company filings"]),
    "EA": ("none", "Electronic Arts: tidak ada laporan signifikan.", ["Company filings"]),
    "SNAP": ("none", "Snap Inc: tidak ada laporan signifikan.", ["Company filings"]),
    "PINS": ("none", "Pinterest: tidak ada laporan signifikan.", ["Company filings"]),
    "RDDT": ("none", "Reddit: tidak ada laporan signifikan.", ["Company filings"]),
    "HOOD": ("none", "Robinhood: tidak ada laporan signifikan.", ["Company filings"]),
    "COIN": ("none", "Coinbase: tidak ada laporan signifikan.", ["Company filings"]),
    "MSTR": ("none", "MicroStrategy: tidak ada laporan signifikan (perusahaan software/Bitcoin).", ["Company filings"]),
    "RBLX": ("none", "Roblox: tidak ada laporan signifikan.", ["Company filings"]),
    "U": ("none", "Unity Software: tidak ada laporan signifikan.", ["Company filings"]),
    "GME": ("none", "GameStop: tidak ada laporan signifikan.", ["Company filings"]),
    "RACE": ("none", "Ferrari: tidak ada laporan signifikan.", ["Company filings"]),
    "TM": ("none", "Toyota Motor: tidak ada laporan signifikan.", ["Company filings"]),
    "SONY": ("none", "Sony Group: tidak ada laporan signifikan.", ["Company filings"]),
    "WMG": ("none", "Warner Music Group: tidak ada laporan signifikan.", ["Company filings"]),
    "LYV": ("none", "Live Nation Entertainment: tidak ada laporan signifikan.", ["Company filings"]),
    "TKO": ("none", "TKO Group (UFC/WWE): tidak ada laporan signifikan.", ["Company filings"]),
    "NYT": ("none", "New York Times: tidak ada laporan signifikan terkait afiliasi bisnis.", ["Company filings"]),
    "OMC": ("none", "Omnicom Group: tidak ada laporan signifikan.", ["Company filings"]),
    "FOX": ("none", "Fox Corporation: tidak ada laporan signifikan.", ["Company filings"]),
    "FOXA": ("none", "Fox Corporation (A): tidak ada laporan signifikan.", ["Company filings"]),
    "TME": ("none", "Tencent Music: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "NTES": ("none", "NetEase: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "BIDU": ("none", "Baidu: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "JD": ("none", "JD.com: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "BABA": ("none", "Alibaba: tidak ada laporan signifikan — sudah ada di DB (none).", ["Company filings"]),
    "TCOM": ("none", "Trip.com: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "VIPS": ("none", "Vipshop: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "BEKE": ("none", "KE Holdings: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "CPNG": ("none", "Coupang: perusahaan Korea/AS, tidak ada laporan signifikan.", ["Company filings"]),
    "GRAB": ("none", "Grab Holdings: perusahaan Asia Tenggara, tidak ada laporan signifikan.", ["Company filings"]),
    "MELI": ("none", "MercadoLibre: tidak ada laporan signifikan.", ["Company filings"]),
    "SE": ("none", "Sea Limited: tidak ada laporan signifikan.", ["Company filings"]),
    "NU": ("none", "Nu Holdings: tidak ada laporan signifikan.", ["Company filings"]),
    "FUTU": ("none", "Futu Holdings: perusahaan Hong Kong, tidak ada laporan signifikan.", ["Company filings"]),
    "XPEV": ("none", "XPeng: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "NIO": ("none", "NIO Inc: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "LI": ("none", "Li Auto: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "RIVN": ("none", "Rivian: tidak ada laporan signifikan.", ["Company filings"]),
    "LCID": ("none", "Lucid Group: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Perjalanan / Transportasi ─────────────────────────────────────────────
    "UBER": ("none", "Uber: tidak ada laporan signifikan.", ["Company filings"]),
    "LYFT": ("none", "Lyft: tidak ada laporan signifikan.", ["Company filings"]),
    "DASH": ("none", "DoorDash: tidak ada laporan signifikan.", ["Company filings"]),
    "EXPE": ("none", "Expedia: tidak ada laporan signifikan.", ["Company filings"]),
    "DAL": ("none", "Delta Air Lines: tidak ada laporan signifikan.", ["Company filings"]),
    "UAL": ("none", "United Airlines: tidak ada laporan signifikan.", ["Company filings"]),
    "AAL": ("none", "American Airlines: tidak ada laporan signifikan.", ["Company filings"]),
    "LUV": ("none", "Southwest Airlines: tidak ada laporan signifikan.", ["Company filings"]),
    "JBLU": ("none", "JetBlue: tidak ada laporan signifikan.", ["Company filings"]),
    "RYAAY": ("none", "Ryanair: tidak ada laporan signifikan.", ["Company filings"]),
    "FDX": ("none", "FedEx: tidak ada laporan signifikan.", ["Company filings"]),
    "UPS": ("none", "UPS: tidak ada laporan signifikan.", ["Company filings"]),
    "ODFL": ("none", "Old Dominion Freight: tidak ada laporan signifikan.", ["Company filings"]),
    "JBHT": ("none", "J.B. Hunt Transport: tidak ada laporan signifikan.", ["Company filings"]),
    "CHRW": ("none", "C.H. Robinson: tidak ada laporan signifikan.", ["Company filings"]),
    "EXPD": ("none", "Expeditors International: tidak ada laporan signifikan.", ["Company filings"]),
    "CSX": ("none", "CSX Corporation: tidak ada laporan signifikan.", ["Company filings"]),
    "UNP": ("none", "Union Pacific: tidak ada laporan signifikan.", ["Company filings"]),
    "NSC": ("none", "Norfolk Southern: tidak ada laporan signifikan.", ["Company filings"]),
    "CNI": ("none", "Canadian National Railway: tidak ada laporan signifikan.", ["Company filings"]),
    "RJF": ("none", "Raymond James Financial: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Real Estate ───────────────────────────────────────────────────────────
    "AMT": ("none", "American Tower: tidak ada laporan signifikan.", ["Company filings"]),
    "EQIX": ("none", "Equinix: tidak ada laporan signifikan.", ["Company filings"]),
    "DLR": ("none", "Digital Realty: tidak ada laporan signifikan.", ["Company filings"]),
    "CCI": ("none", "Crown Castle: tidak ada laporan signifikan.", ["Company filings"]),
    "SPG": ("none", "Simon Property Group: tidak ada laporan signifikan.", ["Company filings"]),
    "PLD": ("none", "Prologis: tidak ada laporan signifikan.", ["Company filings"]),
    "VICI": ("none", "VICI Properties: tidak ada laporan signifikan.", ["Company filings"]),
    "ESS": ("none", "Essex Property Trust: tidak ada laporan signifikan.", ["Company filings"]),
    "PSA": ("none", "Public Storage: tidak ada laporan signifikan.", ["Company filings"]),
    "EXR": ("none", "Extra Space Storage: tidak ada laporan signifikan.", ["Company filings"]),
    "IRM": ("none", "Iron Mountain: tidak ada laporan signifikan.", ["Company filings"]),
    "CUBE": ("none", "CubeSmart: tidak ada laporan signifikan.", ["Company filings"]),
    "NLY": ("none", "Annaly Capital: tidak ada laporan signifikan.", ["Company filings"]),
    "AGNC": ("none", "AGNC Investment: tidak ada laporan signifikan.", ["Company filings"]),
    "AMH": ("none", "American Homes 4 Rent: tidak ada laporan signifikan.", ["Company filings"]),
    "ARE": ("none", "Alexandria Real Estate: tidak ada laporan signifikan.", ["Company filings"]),
    "BIP": ("none", "Brookfield Infrastructure: tidak ada laporan signifikan.", ["Company filings"]),
    "ARCC": ("none", "Ares Capital: tidak ada laporan signifikan.", ["Company filings"]),
    "MAIN": ("none", "Main Street Capital: tidak ada laporan signifikan.", ["Company filings"]),
    "EPR": ("none", "EPR Properties: tidak ada laporan signifikan.", ["Company filings"]),
    "IIPR": ("none", "Innovative Industrial Properties: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Teknologi Lainnya ─────────────────────────────────────────────────────
    "SPOT": ("none", "Spotify: berkantor pusat di Swedia, tidak ada laporan signifikan.", ["Company filings"]),
    "SHOP": ("none", "Shopify: perusahaan Kanada, tidak ada laporan signifikan.", ["Company filings"]),
    "NOW": ("none", "ServiceNow: tidak ada laporan signifikan.", ["Company filings"]),
    "WDAY": ("none", "Workday: tidak ada laporan signifikan.", ["Company filings"]),
    "APP": ("none", "AppLovin: tidak ada laporan signifikan.", ["Company filings"]),
    "DDOG": ("none", "Datadog: tidak ada laporan signifikan.", ["Company filings"]),
    "NET": ("none", "Cloudflare: tidak ada laporan signifikan.", ["Company filings"]),
    "CRWD": ("low",
        "CrowdStrike: beberapa laporan tentang layanan keamanan siber ke entitas pemerintah Israel. Tidak masuk daftar BDS utama.",
        ["AFSC Investigate (partial)"]),
    "FTNT": ("none", "Fortinet: tidak ada laporan signifikan.", ["Company filings"]),
    "ZS": ("none", "Zscaler: tidak ada laporan signifikan.", ["Company filings"]),
    "OKTA": ("none", "Okta: tidak ada laporan signifikan.", ["Company filings"]),
    "TEAM": ("none", "Atlassian: perusahaan Australia, tidak ada laporan signifikan.", ["Company filings"]),
    "HUBS": ("none", "HubSpot: tidak ada laporan signifikan.", ["Company filings"]),
    "TTD": ("none", "The Trade Desk: tidak ada laporan signifikan.", ["Company filings"]),
    "SNAP": ("none", "Snap Inc: tidak ada laporan signifikan.", ["Company filings"]),
    "PINS": ("none", "Pinterest: tidak ada laporan signifikan.", ["Company filings"]),
    "TWLO": ("none", "Twilio: tidak ada laporan signifikan.", ["Company filings"]),
    "ZM": ("none", "Zoom Video: tidak ada laporan signifikan.", ["Company filings"]),
    "DOCU": ("none", "DocuSign: tidak ada laporan signifikan.", ["Company filings"]),
    "PATH": ("none", "UiPath: tidak ada laporan signifikan.", ["Company filings"]),
    "MDB": ("none", "MongoDB: tidak ada laporan signifikan.", ["Company filings"]),
    "SNOW": ("none", "Snowflake: tidak ada laporan signifikan.", ["Company filings"]),
    "ESTC": ("none", "Elastic NV: tidak ada laporan signifikan.", ["Company filings"]),
    "GTLB": ("none", "GitLab: tidak ada laporan signifikan.", ["Company filings"]),
    "IOT": ("none", "Samsara: tidak ada laporan signifikan.", ["Company filings"]),
    "SOUN": ("none", "SoundHound AI: tidak ada laporan signifikan.", ["Company filings"]),
    "IONQ": ("none", "IonQ: tidak ada laporan signifikan.", ["Company filings"]),
    "QBTS": ("none", "D-Wave Quantum: tidak ada laporan signifikan.", ["Company filings"]),
    "RGTI": ("none", "Rigetti Computing: tidak ada laporan signifikan.", ["Company filings"]),
    "ASTS": ("none", "AST SpaceMobile: tidak ada laporan signifikan.", ["Company filings"]),
    "RKLB": ("none", "Rocket Lab: tidak ada laporan signifikan.", ["Company filings"]),
    "ACHR": ("none", "Archer Aviation: tidak ada laporan signifikan.", ["Company filings"]),
    "JOBY": ("none", "Joby Aviation: tidak ada laporan signifikan.", ["Company filings"]),
    "SMR": ("none", "NuScale Power: tidak ada laporan signifikan.", ["Company filings"]),
    "OKLO": ("none", "Oklo Inc: tidak ada laporan signifikan.", ["Company filings"]),
    "VST": ("none", "Vistra Corp: tidak ada laporan signifikan.", ["Company filings"]),
    "FSLR": ("none", "First Solar: tidak ada laporan signifikan.", ["Company filings"]),
    "ENPH": ("none", "Enphase Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "PLUG": ("none", "Plug Power: tidak ada laporan signifikan.", ["Company filings"]),
    "PYPL": ("medium",
        "PayPal: telah mendiskriminasi pengguna Palestina — memblokir akun dan layanan di Gaza/Tepi Barat sementara layanan Israel berjalan normal.",
        ["Human Rights Watch (2021)", "Mondoweiss", "Electronic Intifada"]),
    "GDDY": ("none", "GoDaddy: tidak ada laporan signifikan.", ["Company filings"]),
    "CDW": ("none", "CDW Corporation: tidak ada laporan signifikan.", ["Company filings"]),
    "NTAP": ("none", "NetApp: tidak ada laporan signifikan.", ["Company filings"]),
    "WDC": ("none", "Western Digital: tidak ada laporan signifikan.", ["Company filings"]),
    "STX": ("none", "Seagate Technology: tidak ada laporan signifikan.", ["Company filings"]),
    "HPQ": ("low",
        "HP Inc (HPQ): spin-off dari Hewlett-Packard. Mewarisi koneksi ke sistem biometrik dan printer di pos pemeriksaan Israel, meski lebih sedikit dari HPE.",
        ["Who Profits (partial)", "BDS Movement"]),
    "INFY": ("none", "Infosys: perusahaan India, tidak ada laporan signifikan.", ["Company filings"]),
    "WIT": ("none", "Wipro: perusahaan India, tidak ada laporan signifikan.", ["Company filings"]),
    "CTSH": ("none", "Cognizant: tidak ada laporan signifikan.", ["Company filings"]),
    "ACM": ("none", "AECOM: tidak ada laporan signifikan.", ["Company filings"]),
    "MANH": ("none", "Manhattan Associates: tidak ada laporan signifikan.", ["Company filings"]),
    "SAP": ("low",
        "SAP SE: perangkat lunak ERP digunakan oleh perusahaan dan entitas pemerintah Israel. Tidak spesifik militer, tapi ada kehadiran operasional di Israel.",
        ["Company disclosures"]),

    # ── Kesehatan / Asuransi ──────────────────────────────────────────────────
    "UNH": ("none", "UnitedHealth Group: tidak ada laporan signifikan.", ["Company filings"]),
    "CVS": ("none", "CVS Health: tidak ada laporan signifikan.", ["Company filings"]),
    "HCA": ("none", "HCA Healthcare: tidak ada laporan signifikan.", ["Company filings"]),
    "CI": ("none", "Cigna: tidak ada laporan signifikan.", ["Company filings"]),
    "HUM": ("none", "Humana: tidak ada laporan signifikan.", ["Company filings"]),
    "CNC": ("none", "Centene: tidak ada laporan signifikan.", ["Company filings"]),
    "MCK": ("none", "McKesson: tidak ada laporan signifikan.", ["Company filings"]),
    "CAH": ("none", "Cardinal Health: tidak ada laporan signifikan.", ["Company filings"]),
    "ABC": ("none", "AmerisourceBergen: tidak ada laporan signifikan.", ["Company filings"]),
    "DGX": ("none", "Quest Diagnostics: tidak ada laporan signifikan.", ["Company filings"]),
    "LH": ("none", "Labcorp: tidak ada laporan signifikan.", ["Company filings"]),
    "HSIC": ("none", "Henry Schein: tidak ada laporan signifikan.", ["Company filings"]),
    "DVA": ("none", "DaVita: tidak ada laporan signifikan.", ["Company filings"]),
    "THC": ("none", "Tenet Healthcare: tidak ada laporan signifikan.", ["Company filings"]),
    "HUM": ("none", "Humana: tidak ada laporan signifikan.", ["Company filings"]),
    "MOH": ("none", "Molina Healthcare: tidak ada laporan signifikan.", ["Company filings"]),
    "OSCR": ("none", "Oscar Health: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Bank / Perbankan internasional ────────────────────────────────────────
    "HSBC": ("medium",
        "HSBC: bank global yang memfasilitasi transaksi keuangan untuk entitas Israel dan underwriting obligasi pemerintah Israel.",
        ["AFSC Investigate (financial)", "Who Profits (partial)"]),
    "DB": ("medium",
        "Deutsche Bank: operasi perbankan di Israel, termasuk layanan untuk perusahaan-perusahaan yang beroperasi di wilayah pendudukan.",
        ["Who Profits (partial)", "AFSC Investigate"]),
    "BBVA": ("none", "BBVA: bank Spanyol, tidak ada laporan signifikan terkait Israel.", ["Company filings"]),
    "SAN": ("none", "Banco Santander: tidak ada laporan signifikan.", ["Company filings"]),
    "ING": ("none", "ING Group: tidak ada laporan signifikan.", ["Company filings"]),
    "BCS": ("none", "Barclays: tidak ada laporan signifikan terkait Israel.", ["Company filings"]),
    "RY": ("none", "Royal Bank of Canada: tidak ada laporan signifikan.", ["Company filings"]),
    "TD": ("none", "Toronto-Dominion Bank: tidak ada laporan signifikan.", ["Company filings"]),
    "BMO": ("none", "Bank of Montreal: tidak ada laporan signifikan.", ["Company filings"]),
    "BNS": ("none", "Bank of Nova Scotia: tidak ada laporan signifikan.", ["Company filings"]),
    "MFC": ("none", "Manulife Financial: tidak ada laporan signifikan.", ["Company filings"]),
    "KB": ("none", "KB Financial (Korea): tidak ada laporan signifikan.", ["Company filings"]),

    # ── Pertambangan / Logam Mulia ────────────────────────────────────────────
    "WPM": ("none", "Wheaton Precious Metals: tidak ada laporan signifikan.", ["Company filings"]),
    "AEM": ("none", "Agnico Eagle Mines: tidak ada laporan signifikan.", ["Company filings"]),
    "KGC": ("none", "Kinross Gold: tidak ada laporan signifikan.", ["Company filings"]),
    "GFI": ("none", "Gold Fields: tidak ada laporan signifikan.", ["Company filings"]),
    "HMY": ("none", "Harmony Gold: tidak ada laporan signifikan.", ["Company filings"]),
    "NEM": ("none", "Newmont: tidak ada laporan signifikan.", ["Company filings"]),
    "AU": ("none", "AngloGold Ashanti: tidak ada laporan signifikan.", ["Company filings"]),
    "WPM": ("none", "Wheaton Precious Metals: tidak ada laporan signifikan.", ["Company filings"]),
    "SBSW": ("none", "Sibanye Stillwater: tidak ada laporan signifikan.", ["Company filings"]),
    "PAAS": ("none", "Pan American Silver: tidak ada laporan signifikan.", ["Company filings"]),
    "SCCO": ("none", "Southern Copper: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Rokok / Tembakau ──────────────────────────────────────────────────────
    "PM": ("none", "Philip Morris International: tidak ada laporan signifikan.", ["Company filings"]),
    "MO": ("none", "Altria Group: tidak ada laporan signifikan.", ["Company filings"]),
    "BTI": ("none", "British American Tobacco: tidak ada laporan signifikan.", ["Company filings"]),
    "DEO": ("none", "Diageo: tidak ada laporan signifikan.", ["Company filings"]),
    "BUD": ("none", "AB InBev: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Konstruksi / Properti ─────────────────────────────────────────────────
    "DHI": ("none", "D.R. Horton: tidak ada laporan signifikan.", ["Company filings"]),
    "LEN": ("none", "Lennar: tidak ada laporan signifikan.", ["Company filings"]),
    "PHM": ("none", "PulteGroup: tidak ada laporan signifikan.", ["Company filings"]),
    "TOL": ("none", "Toll Brothers: tidak ada laporan signifikan.", ["Company filings"]),
    "MTZ": ("none", "MasTec: tidak ada laporan signifikan.", ["Company filings"]),
    "JLL": ("none", "Jones Lang LaSalle: tidak ada laporan signifikan.", ["Company filings"]),
    "CBRE": ("none", "CBRE Group: tidak ada laporan signifikan.", ["Company filings"]),
    "GXO": ("none", "GXO Logistics: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Asuransi ──────────────────────────────────────────────────────────────
    "PGR": ("none", "Progressive: tidak ada laporan signifikan.", ["Company filings"]),
    "CB": ("none", "Chubb: tidak ada laporan signifikan.", ["Company filings"]),
    "ALL": ("none", "Allstate: tidak ada laporan signifikan.", ["Company filings"]),
    "CINF": ("none", "Cincinnati Financial: tidak ada laporan signifikan.", ["Company filings"]),
    "AFG": ("none", "American Financial Group: tidak ada laporan signifikan.", ["Company filings"]),
    "AON": ("none", "Aon: tidak ada laporan signifikan.", ["Company filings"]),
    "MMC": ("none", "Marsh & McLennan: tidak ada laporan signifikan.", ["Company filings"]),
    "WTW": ("none", "Willis Towers Watson: tidak ada laporan signifikan.", ["Company filings"]),
    "SPGI": ("low", "S&P Global: rating obligasi Israel. Tidak ada keterlibatan langsung lebih jauh.", ["AFSC Investigate (partial)"]),
    "MCO": ("low", "Moody's: rating obligasi Israel.", ["AFSC Investigate (partial)"]),

    # ── Pembayaran Digital ────────────────────────────────────────────────────
    "SQ": ("none", "Block (Square): tidak ada laporan signifikan.", ["Company filings"]),
    "AFRM": ("none", "Affirm: tidak ada laporan signifikan.", ["Company filings"]),
    "SOFI": ("none", "SoFi Technologies: tidak ada laporan signifikan.", ["Company filings"]),
    "BILL": ("none", "Bill.com: tidak ada laporan signifikan.", ["Company filings"]),
    "PAYO": ("none", "Payoneer: tidak ada laporan signifikan.", ["Company filings"]),
    "WU": ("none", "Western Union: tidak ada laporan signifikan.", ["Company filings"]),

    # ── Lain-lain ─────────────────────────────────────────────────────────────
    "BRK.B": ("medium",
        "Berkshire Hathaway: portofolio investasi Warren Buffett mencakup perusahaan-perusahaan dengan eksposur ke Israel, termasuk JPMorgan dan Bank of America historis.",
        ["AFSC Investigate (portfolio exposure)"]),
    "FCNCA": ("none", "First Citizens BancShares: tidak ada laporan signifikan.", ["Company filings"]),
    "PBR": ("none", "Petrobras: perusahaan Brazil, tidak ada laporan signifikan.", ["Company filings"]),
    "PUK": ("none", "Prudential plc (UK): tidak ada laporan signifikan.", ["Company filings"]),
    "STM": ("none", "STMicroelectronics: tidak ada laporan signifikan.", ["Company filings"]),
    "ASX": ("none", "ASE Technology (Taiwan): tidak ada laporan signifikan.", ["Company filings"]),
    "UMC": ("none", "United Microelectronics (Taiwan): tidak ada laporan signifikan.", ["Company filings"]),
    "MANU": ("none", "Manchester United: tidak ada laporan signifikan.", ["Company filings"]),
    "IT": ("none", "Gartner: tidak ada laporan signifikan.", ["Company filings"]),
    "IDXX": ("none", "IDEXX Laboratories: tidak ada laporan signifikan.", ["Company filings"]),
    "VRSN": ("none", "VeriSign: tidak ada laporan signifikan.", ["Company filings"]),
    "AKAM": ("none", "Akamai Technologies: tidak ada laporan signifikan.", ["Company filings"]),
    "LUMN": ("none", "Lumen Technologies: tidak ada laporan signifikan.", ["Company filings"]),
    "INCY": ("none", "Incyte: tidak ada laporan signifikan.", ["Company filings"]),
    "VTRS": ("none", "Viatris: tidak ada laporan signifikan.", ["Company filings"]),
    "ILMN": ("none", "Illumina: tidak ada laporan signifikan.", ["Company filings"]),
    "BIO": ("none", "Bio-Rad Laboratories: tidak ada laporan signifikan.", ["Company filings"]),
    "RVTY": ("none", "Revvity: tidak ada laporan signifikan.", ["Company filings"]),
    "A": ("none", "Agilent Technologies: tidak ada laporan signifikan.", ["Company filings"]),
    "TMDX": ("none", "TransMedics Group: tidak ada laporan signifikan.", ["Company filings"]),
    "CELH": ("none", "Celsius Holdings: tidak ada laporan signifikan.", ["Company filings"]),
    "MNSO": ("none", "MINISO Group: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "DUOL": ("none", "Duolingo: tidak ada laporan signifikan.", ["Company filings"]),
    "DJT": ("none", "Trump Media & Technology Group: tidak ada laporan signifikan.", ["Company filings"]),
    "CVNA": ("none", "Carvana: tidak ada laporan signifikan.", ["Company filings"]),
    "UPST": ("none", "Upstart Holdings: tidak ada laporan signifikan.", ["Company filings"]),
    "HOOD": ("none", "Robinhood: tidak ada laporan signifikan.", ["Company filings"]),
    "COIN": ("none", "Coinbase: tidak ada laporan signifikan.", ["Company filings"]),
    "MARA": ("none", "Marathon Digital: tidak ada laporan signifikan.", ["Company filings"]),
    "RIOT": ("none", "Riot Platforms: tidak ada laporan signifikan.", ["Company filings"]),
    "CLSK": ("none", "CleanSpark: tidak ada laporan signifikan.", ["Company filings"]),
    "HUT": ("none", "Hut 8 Corp: tidak ada laporan signifikan.", ["Company filings"]),
    "IREN": ("none", "Iris Energy: tidak ada laporan signifikan.", ["Company filings"]),
    "WULF": ("none", "TeraWulf: tidak ada laporan signifikan.", ["Company filings"]),
    "APLD": ("none", "Applied Digital: tidak ada laporan signifikan.", ["Company filings"]),
    "CORZ": ("none", "Core Scientific: tidak ada laporan signifikan.", ["Company filings"]),
    "CIFR": ("none", "Cipher Mining: tidak ada laporan signifikan.", ["Company filings"]),
    "BTBT": ("none", "Bit Digital: tidak ada laporan signifikan.", ["Company filings"]),
    "NE": ("none", "Noble Corporation: tidak ada laporan signifikan.", ["Company filings"]),
    "RIG": ("none", "Transocean: tidak ada laporan signifikan.", ["Company filings"]),
    "TDW": ("none", "Tidewater: tidak ada laporan signifikan.", ["Company filings"]),
    "NNDM": ("high",
        "Nano Dimension: perusahaan Israel yang berkantor pusat di Nes Ziona. Manufaktur elektronik aditif, sebagian untuk aplikasi pertahanan.",
        ["Company HQ: Nes Ziona, Israel", "Company disclosures"]),
    "MBLY": ("high",
        "Mobileye: perusahaan teknologi kendaraan otonom yang didirikan di Israel (Jerusalem). Anak perusahaan Intel, berkantor pusat di Jerusalem.",
        ["Company HQ: Jerusalem, Israel", "Intel acquisition disclosure"]),
    "NBIS": ("none", "Nebius Group: tidak ada laporan signifikan.", ["Company filings"]),
    "SMMT": ("none", "Summit Therapeutics: tidak ada laporan signifikan.", ["Company filings"]),
    "HIMS": ("none", "Hims & Hers Health: tidak ada laporan signifikan.", ["Company filings"]),
    "CRON": ("none", "Cronos Group: tidak ada laporan signifikan.", ["Company filings"]),
    "TLRY": ("none", "Tilray Brands: tidak ada laporan signifikan.", ["Company filings"]),
    "CGC": ("none", "Canopy Growth: tidak ada laporan signifikan.", ["Company filings"]),
    "AMC": ("none", "AMC Entertainment: tidak ada laporan signifikan.", ["Company filings"]),
    "BYND": ("none", "Beyond Meat: tidak ada laporan signifikan.", ["Company filings"]),
    "PTON": ("none", "Peloton Interactive: tidak ada laporan signifikan.", ["Company filings"]),
    "TDOC": ("none", "Teladoc Health: tidak ada laporan signifikan.", ["Company filings"]),
    "ZM": ("none", "Zoom Video: tidak ada laporan signifikan.", ["Company filings"]),
    "SYM": ("none", "Symbotic: tidak ada laporan signifikan.", ["Company filings"]),
    "AXON": ("low",
        "Axon Enterprise (TASER): produk senjata non-lethal yang dijual ke berbagai aparat keamanan termasuk kemungkinan Israel. Tidak ada laporan spesifik.",
        ["Company filings"]),
    "HOG": ("none", "Harley-Davidson: tidak ada laporan signifikan.", ["Company filings"]),
    "BC": ("none", "Brunswick Corporation: tidak ada laporan signifikan.", ["Company filings"]),
    "NAK": ("none", "Northern Dynasty: tidak ada laporan signifikan.", ["Company filings"]),
    "HL": ("none", "Hecla Mining: tidak ada laporan signifikan.", ["Company filings"]),
    "SLNO": ("none", "Soleno Therapeutics: tidak ada laporan signifikan.", ["Company filings"]),
    "BF.B": ("none", "Brown-Forman: tidak ada laporan signifikan.", ["Company filings"]),
    "TEM": ("none", "Tempus AI: tidak ada laporan signifikan.", ["Company filings"]),
    "LMND": ("none", "Lemonade: tidak ada laporan signifikan.", ["Company filings"]),
    "COUR": ("none", "Coursera: tidak ada laporan signifikan.", ["Company filings"]),
    "CHWY": ("none", "Chewy: tidak ada laporan signifikan.", ["Company filings"]),
    "DNUT": ("none", "Krispy Kreme: tidak ada laporan signifikan.", ["Company filings"]),
    "WEN": ("none", "Wendy's: tidak ada laporan signifikan.", ["Company filings"]),
    "JACK": ("none", "Jack in the Box: tidak ada laporan signifikan.", ["Company filings"]),
    "ARKO": ("none", "Arko Corp: tidak ada laporan signifikan.", ["Company filings"]),
    "NMR": ("none", "Nomura Holdings: perusahaan Jepang, tidak ada laporan signifikan.", ["Company filings"]),
    "KEP": ("none", "Korea Electric Power: tidak ada laporan signifikan.", ["Company filings"]),
    "PDD": ("none", "PDD Holdings (Temu/Pinduoduo): perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "SMCI": ("none", "Super Micro Computer: tidak ada laporan signifikan.", ["Company filings"]),
    "VRT": ("none", "Vertiv Holdings: tidak ada laporan signifikan.", ["Company filings"]),
    "CLS": ("none", "Celestica: tidak ada laporan signifikan.", ["Company filings"]),
    "JBL": ("none", "Jabil: tidak ada laporan signifikan.", ["Company filings"]),
    "FN": ("none", "Fabrinet: tidak ada laporan signifikan.", ["Company filings"]),
    "ONTO": ("none", "Onto Innovation: tidak ada laporan signifikan.", ["Company filings"]),
    "ENTG": ("none", "Entegris: tidak ada laporan signifikan.", ["Company filings"]),
    "MPWR": ("none", "Monolithic Power Systems: tidak ada laporan signifikan.", ["Company filings"]),
    "CRDO": ("none", "Credo Technology: tidak ada laporan signifikan.", ["Company filings"]),
    "SITM": ("none", "SiTime Corporation: tidak ada laporan signifikan.", ["Company filings"]),
    "ACMR": ("none", "ACM Research: tidak ada laporan signifikan.", ["Company filings"]),
    "PI": ("none", "Impinj: tidak ada laporan signifikan.", ["Company filings"]),
    "AXTI": ("none", "AXT Inc: tidak ada laporan signifikan.", ["Company filings"]),
    "ENVX": ("none", "Enovix: tidak ada laporan signifikan.", ["Company filings"]),
    "QS": ("none", "QuantumScape: tidak ada laporan signifikan.", ["Company filings"]),
    "PLUG": ("none", "Plug Power: tidak ada laporan signifikan.", ["Company filings"]),
    "RUN": ("none", "Sunrun: tidak ada laporan signifikan.", ["Company filings"]),
    "SEDG": ("high",
        "SolarEdge Technologies: perusahaan teknologi surya yang didirikan dan berkantor pusat di Israel (Herzliya). Perusahaan Israel yang listing di NASDAQ.",
        ["Company HQ: Herzliya, Israel", "Company disclosures"]),
    "FVRR": ("none", "Fiverr International: berkantor pusat di Tel Aviv, Israel — perusahaan Israel.", ["Company HQ: Tel Aviv, Israel"]),
    "MNDY": ("high",
        "Monday.com: perusahaan SaaS yang berkantor pusat di Tel Aviv, Israel. Perusahaan Israel.",
        ["Company HQ: Tel Aviv, Israel"]),
    "WIX": ("high",
        "Wix.com: platform web hosting yang berkantor pusat di Tel Aviv, Israel. Perusahaan Israel.",
        ["Company HQ: Tel Aviv, Israel"]),
    "NICE": ("high",
        "NICE Systems: perusahaan teknologi berkantor pusat di Ra'anana, Israel.",
        ["Company HQ: Ra'anana, Israel"]),
    "GLBE": ("high",
        "Global-E Online: solusi e-commerce cross-border, berkantor pusat di Petah Tikva, Israel.",
        ["Company HQ: Petah Tikva, Israel"]),
    "ZETA": ("none", "Zeta Global: tidak ada laporan signifikan.", ["Company filings"]),
    "RELY": ("none", "Remitly Global: tidak ada laporan signifikan.", ["Company filings"]),
    "MMYT": ("none", "MakeMyTrip: perusahaan India, tidak ada laporan signifikan.", ["Company filings"]),
    "BILL": ("none", "Bill.com: tidak ada laporan signifikan.", ["Company filings"]),
    "DOCN": ("none", "DigitalOcean: tidak ada laporan signifikan.", ["Company filings"]),
    "BOX": ("none", "Box Inc: tidak ada laporan signifikan.", ["Company filings"]),
    "DBX": ("none", "Dropbox: tidak ada laporan signifikan.", ["Company filings"]),
    "IAC": ("none", "IAC Inc: tidak ada laporan signifikan.", ["Company filings"]),
    "MTCH": ("none", "Match Group: tidak ada laporan signifikan.", ["Company filings"]),
    "ZG": ("none", "Zillow Group: tidak ada laporan signifikan.", ["Company filings"]),
    "Z": ("none", "Zillow Group (C): tidak ada laporan signifikan.", ["Company filings"]),
    "OPEN": ("none", "Opendoor: tidak ada laporan signifikan.", ["Company filings"]),
    "ASAN": ("none", "Asana: tidak ada laporan signifikan.", ["Company filings"]),
    "APPN": ("none", "Appian: tidak ada laporan signifikan.", ["Company filings"]),
    "BAND": ("none", "Bandwidth Inc: tidak ada laporan signifikan.", ["Company filings"]),
    "FSLY": ("none", "Fastly: tidak ada laporan signifikan.", ["Company filings"]),
    "NTNX": ("none", "Nutanix: tidak ada laporan signifikan.", ["Company filings"]),
    "CVLT": ("none", "Commvault: tidak ada laporan signifikan.", ["Company filings"]),
    "FIVN": ("none", "Five9: tidak ada laporan signifikan.", ["Company filings"]),
    "PCTY": ("none", "Paylocity: tidak ada laporan signifikan.", ["Company filings"]),
    "PAYC": ("none", "Paycom Software: tidak ada laporan signifikan.", ["Company filings"]),
    "PAYX": ("none", "Paychex: tidak ada laporan signifikan.", ["Company filings"]),
    "ADP": ("none", "Automatic Data Processing: tidak ada laporan signifikan.", ["Company filings"]),
    "G": ("none", "Genpact: tidak ada laporan signifikan.", ["Company filings"]),
    "EPAM": ("none", "EPAM Systems: tidak ada laporan signifikan.", ["Company filings"]),
    "OKTA": ("none", "Okta: tidak ada laporan signifikan.", ["Company filings"]),
    "DDOG": ("none", "Datadog: tidak ada laporan signifikan.", ["Company filings"]),
    "WDAY": ("none", "Workday: tidak ada laporan signifikan.", ["Company filings"]),
    "CRM": ("medium",
        "Salesforce: sudah ada di database (medium).",
        ["Who Profits (partial)"]),
    "NOW": ("none", "ServiceNow: tidak ada laporan signifikan.", ["Company filings"]),
    "ADBE": ("none", "Adobe: tidak ada laporan signifikan — sudah ada di DB.", ["Company filings"]),
    "LOGI": ("none", "Logitech: berkantor pusat di Swiss, tidak ada laporan signifikan.", ["Company filings"]),
    "SONO": ("none", "Sonos: tidak ada laporan signifikan.", ["Company filings"]),
    "VZIO": ("none", "VIZIO: tidak ada laporan signifikan.", ["Company filings"]),
    "AI": ("none", "C3.ai: tidak ada laporan signifikan.", ["Company filings"]),
    "BBAI": ("none", "BigBear.ai: tidak ada laporan signifikan.", ["Company filings"]),
    "SOUN": ("none", "SoundHound AI: tidak ada laporan signifikan.", ["Company filings"]),
    "AMPL": ("none", "Amplitude: tidak ada laporan signifikan.", ["Company filings"]),
    "PUBM": ("none", "PubMatic: tidak ada laporan signifikan.", ["Company filings"]),
    "MGNI": ("none", "Magnite: tidak ada laporan signifikan.", ["Company filings"]),
    "IS": ("none", "IronSource: tidak ada laporan signifikan.", ["Company filings"]),
    "CRSR": ("none", "Corsair Gaming: tidak ada laporan signifikan.", ["Company filings"]),
    "GPRO": ("none", "GoPro: tidak ada laporan signifikan.", ["Company filings"]),
    "ROKU": ("none", "Roku: tidak ada laporan signifikan.", ["Company filings"]),
    "FUBO": ("none", "Fubo TV: tidak ada laporan signifikan.", ["Company filings"]),
    "WK": ("none", "Workiva: tidak ada laporan signifikan.", ["Company filings"]),
    "TRIP": ("none", "Tripadvisor: tidak ada laporan signifikan.", ["Company filings"]),
    "ANGI": ("none", "Angi Inc: tidak ada laporan signifikan.", ["Company filings"]),
    "IAG": ("none", "IAG Silver: tidak ada laporan signifikan.", ["Company filings"]),
    "GCT": ("none", "GigaCloud Technology: tidak ada laporan signifikan.", ["Company filings"]),
    "KC": ("none", "Kingsoft Cloud: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "VNET": ("none", "VNET Group: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "WB": ("none", "Weibo: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "IQ": ("none", "iQIYI: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "BILI": ("none", "Bilibili: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "EH": ("none", "EHang Holdings: perusahaan China, tidak ada laporan signifikan.", ["Company filings"]),
    "XRAY": ("none", "Dentsply Sirona: tidak ada laporan signifikan.", ["Company filings"]),
    "ALGN": ("none", "Align Technology: tidak ada laporan signifikan.", ["Company filings"]),
    "DKNG": ("none", "DraftKings: tidak ada laporan signifikan.", ["Company filings"]),
    "EVERI": ("none", "Everi Holdings: tidak ada laporan signifikan.", ["Company filings"]),
    "GAN": ("none", "GAN Limited: tidak ada laporan signifikan.", ["Company filings"]),
    "HII": ("medium",
        "Huntington Ingalls Industries: galangan kapal militer AS, membangun kapal perang yang dapat beroperasi di Mediterania (dekat Israel). Tidak secara khusus ditargetkan BDS namun pemasok militer AS.",
        ["AFSC Investigate (defense sector)"]),
    "SAIC": ("medium",
        "Science Applications International: kontraktor pertahanan AS dengan kontrak intelijen/militer yang berinteraksi dengan operasi AS di Timur Tengah.",
        ["AFSC Investigate"]),
    "LHX": ("high",
        "L3Harris Technologies: sistem elektronik militer dan komunikasi yang digunakan IDF. Pemasok langsung ke angkatan bersenjata Israel.",
        ["AFSC Investigate", "Who Profits", "Defense contracts"]),
    "AXON": ("low",
        "Axon Enterprise: produk penegakan hukum, ada kemungkinan penjualan ke Israel namun tidak terdokumentasi spesifik.",
        ["Company filings"]),
}

# ── Helpers ────────────────────────────────────────────────────────────────────

def is_etf(ticker: str, name: str) -> bool:
    if ticker.upper() in ETF_TICKERS:
        return True
    name_lower = name.lower()
    return any(p in name_lower for p in ETF_NAME_PATTERNS)


def js_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def patch_block(block: str, tie: str, rationale: str, sources: list[str]) -> str:
    src_str = ", ".join(f'"{js_escape(s)}"' for s in sources)

    block = re.sub(
        r'israelTie:\s*"unknown"[^\n]*',
        f'israelTie: "{tie}",',
        block,
    )
    block = re.sub(
        r'rationale:\s*"Belum dikaji[^"]*"',
        f'rationale: "{js_escape(rationale)}"',
        block,
    )
    block = re.sub(
        r'sources:\s*\["PERLU_REVIEW"\]',
        f'sources: [{src_str}]',
        block,
    )
    return block


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> int:
    text = STOCKS_JS.read_text(encoding="utf-8")

    # Temukan semua ticker dengan israelTie: "unknown".
    # Pattern melewati header fields (no '}' before ethics:{}) lalu masuk ethics block.
    unknown_tickers = re.findall(
        r'ticker:\s*"([^"]+)"[^}]*?ethics:\s*\{[^}]*israelTie:\s*"unknown"',
        text, re.DOTALL,
    )

    if not unknown_tickers:
        print("Tidak ada entri PERLU_REVIEW yang ditemukan.")
        return 0

    print(f"Ditemukan {len(unknown_tickers)} entri untuk direview...\n")

    updated = etf_count = known_count = default_count = 0

    for ticker in unknown_tickers:
        # Temukan posisi entri ini dan batasnya (sampai ticker berikutnya)
        pos = text.find(f'ticker: "{ticker}"')
        if pos < 0:
            continue
        next_pos = text.find('ticker: "', pos + len(ticker) + 10)
        entry_end = next_pos if next_pos > 0 else len(text)
        entry = text[pos:entry_end]

        # Pastikan masih ada "unknown" (mungkin sudah diupdate iterasi sebelumnya)
        if 'israelTie: "unknown"' not in entry:
            continue

        # Lapisan 1: ETF
        name_match = re.search(r'name:\s*"([^"]+)"', entry)
        name = name_match.group(1) if name_match else ""

        if is_etf(ticker, name):
            tie       = "none"
            rationale = "ETF / dana indeks — tidak mengikat ke satu perusahaan spesifik, bukan target boikot BDS."
            sources   = ["ETF classification (auto)"]
            etf_count += 1

        # Lapisan 2: Database bawaan
        elif ticker in KNOWN_ETHICS:
            tie, rationale, sources = KNOWN_ETHICS[ticker]
            sources = sources + ["(auto-klasifikasi, perlu verifikasi)"]
            known_count += 1

        # Lapisan 3: Default konservatif
        else:
            tie       = "none"
            rationale = "Tidak ditemukan dalam laporan publik BDS Movement, Who Profits, AFSC Investigate, atau media kredibel yang mengaitkan perusahaan ini dengan pendudukan Israel. Klasifikasi default konservatif — lakukan verifikasi mandiri."
            sources   = ["(auto-default: tidak ada laporan spesifik ditemukan)"]
            default_count += 1

        new_entry = patch_block(entry, tie, rationale, sources)
        if new_entry != entry:
            text = text[:pos] + new_entry + text[entry_end:]
            updated += 1
            status = "ETF" if "ETF" in sources[0] else tie.upper()
            print(f"  [{status:8}] {ticker:8} {name[:40]}")

    STOCKS_JS.write_text(text, encoding="utf-8")

    print(f"\n{'─'*50}")
    print(f"Selesai. {updated} entri diperbarui.")
    print(f"  ETF/Fund    : {etf_count}")
    print(f"  Database    : {known_count}")
    print(f"  Default     : {default_count}")
    print()
    print("Catatan:")
    print("  · Semua hasil auto-klasifikasi perlu verifikasi mandiri")
    print("  · Cari '(auto-klasifikasi, perlu verifikasi)' untuk entri DB")
    print("  · Cari '(auto-default)' untuk entri yang butuh cek lebih lanjut")
    return 0


if __name__ == "__main__":
    sys.exit(main())
